# Generated by Django 4.1 on 2022-08-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_marking_code', models.CharField(max_length=100)),
                ('account_marking_description', models.CharField(max_length=100)),
                ('mark_for', models.IntegerField(choices=[(0, 'Legal Procedings'), (1, 'Repossesion'), (2, 'Settlement'), (3, 'Skip (Later on)')], default=0)),
                ('marking_level', models.IntegerField(choices=[(0, 'Account Level'), (1, 'Customer level'), (2, 'Case Lavel')], default=0)),
            ],
            options={
                'db_table': 'legal_tbl',
            },
        ),
    ]
