# Generated by Django 4.1 on 2022-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xicor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GokuMstModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
            options={"db_table": "goku_mst",},
        ),
    ]
