# Generated by Django 4.1 on 2022-08-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vegeta", "0001_initial"),
        ("xicor", "0002_gokumstmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="gokumstmodel",
            name="frnd_vegeta",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="vegeta.vegetamstmodel",
                verbose_name="Vegeta mst model",
            ),
            preserve_default=False,
        ),
    ]
