# Generated by Django 4.1 on 2022-08-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xicor", "0004_auto_20220821_2348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gokumstmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="xicormstmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
